package com.mycompany.filnalexam_20182866_nguyenvantuan.view;

import com.mycompany.filnalexam_20182866_nguyenvantuan.controller.Implement.HoDanDAO;
import com.mycompany.filnalexam_20182866_nguyenvantuan.controller.Implement.KhuPhoDAO;
import com.mycompany.filnalexam_20182866_nguyenvantuan.controller.Implement.NguoiDAO;
import com.mycompany.filnalexam_20182866_nguyenvantuan.model.HoDanModel;
import com.mycompany.filnalexam_20182866_nguyenvantuan.model.NguoiModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Van Tuan
 */
public class SuaKhuPhoFrame extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    int indexHoDan = 0;
    int indexNguoi = 0;
    /**
     * Creates new form SuaKhuPhoFrame
     */
    public SuaKhuPhoFrame() {
        initComponents();
    }
    
    public void showTable(List<NguoiModel> listNguoi) {
        tableModel.setRowCount(0);
        for (NguoiModel nguoi : listNguoi) {
            tableModel.addRow(new Object[]{
                nguoi.getMaNguoi(), nguoi.getHoVaTen(), Integer.toString(nguoi.getTuoi()), Integer.toString(nguoi.getNamSinh()), nguoi.getNgheNghiep()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suaKhuPhoLabel = new javax.swing.JLabel();
        saveKhuPhoButton = new javax.swing.JButton();
        backKhuPhoButton = new javax.swing.JButton();
        maKhuPhoLabel = new javax.swing.JLabel();
        maKhuPhoTextField = new javax.swing.JTextField();
        tenKhuPhoLabel = new javax.swing.JLabel();
        tenKhuPhoTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        maNguoiLabel = new javax.swing.JLabel();
        maNguoiTextField = new javax.swing.JTextField();
        hoTenLabel = new javax.swing.JLabel();
        hoTenTextField = new javax.swing.JTextField();
        tuoiLabel = new javax.swing.JLabel();
        tuoiTextField = new javax.swing.JTextField();
        namSinhLabel = new javax.swing.JLabel();
        namSinhTextField = new javax.swing.JTextField();
        ngheNghiepLabel = new javax.swing.JLabel();
        ngheNghiepTextField = new javax.swing.JTextField();
        luuNguoiButton = new javax.swing.JButton();
        thanhVienTruocButton = new javax.swing.JButton();
        thanhVienSauButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        maHoDanLabel = new javax.swing.JLabel();
        maHoDanTextField = new javax.swing.JTextField();
        soNhaLabel = new javax.swing.JLabel();
        soNhaTextField = new javax.swing.JTextField();
        luuHoDanButton = new javax.swing.JButton();
        hoDanTruocButton = new javax.swing.JButton();
        hoDanSauButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        thanhVienTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        suaKhuPhoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        suaKhuPhoLabel.setText("Sửa khu phố");

        saveKhuPhoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveKhuPhoButton.setText("Lưu");
        saveKhuPhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveKhuPhoButtonActionPerformed(evt);
            }
        });

        backKhuPhoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backKhuPhoButton.setText("Back");
        backKhuPhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backKhuPhoButtonActionPerformed(evt);
            }
        });

        maKhuPhoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maKhuPhoLabel.setText("Mã khu phố");

        maKhuPhoTextField.setEnabled(false);

        tenKhuPhoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tenKhuPhoLabel.setText("Tên khu phố");

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        maNguoiLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNguoiLabel.setText("Mã người");

        maNguoiTextField.setEnabled(false);

        hoTenLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hoTenLabel.setText("Họ tên");

        tuoiLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tuoiLabel.setText("Tuổi");

        namSinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namSinhLabel.setText("Năm sinh");

        ngheNghiepLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ngheNghiepLabel.setText("Nghề nghiệp");

        luuNguoiButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        luuNguoiButton.setText("Lưu");
        luuNguoiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuNguoiButtonActionPerformed(evt);
            }
        });

        thanhVienTruocButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thanhVienTruocButton.setText("Thành viên trước");
        thanhVienTruocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhVienTruocButtonActionPerformed(evt);
            }
        });

        thanhVienSauButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thanhVienSauButton.setText("Thành viên sau");
        thanhVienSauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhVienSauButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hoTenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maNguoiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoTenTextField)
                            .addComponent(maNguoiTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(luuNguoiButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(thanhVienTruocButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(thanhVienSauButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngheNghiepLabel)
                            .addComponent(namSinhLabel)
                            .addComponent(tuoiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tuoiTextField)
                            .addComponent(namSinhTextField)
                            .addComponent(ngheNghiepTextField))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maNguoiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNguoiLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoTenLabel)
                    .addComponent(hoTenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuoiLabel)
                    .addComponent(tuoiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namSinhLabel)
                    .addComponent(namSinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngheNghiepLabel)
                    .addComponent(ngheNghiepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(luuNguoiButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thanhVienTruocButton)
                    .addComponent(thanhVienSauButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        maHoDanLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maHoDanLabel.setText("Mã hộ dân");

        maHoDanTextField.setEnabled(false);

        soNhaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        soNhaLabel.setText("Số nhà");

        luuHoDanButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        luuHoDanButton.setText("Lưu");
        luuHoDanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuHoDanButtonActionPerformed(evt);
            }
        });

        hoDanTruocButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hoDanTruocButton.setText("Hộ dân trước");
        hoDanTruocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoDanTruocButtonActionPerformed(evt);
            }
        });

        hoDanSauButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hoDanSauButton.setText("Hộ dân sau");
        hoDanSauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoDanSauButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maHoDanLabel)
                                    .addComponent(soNhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maHoDanTextField)
                                    .addComponent(soNhaTextField)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(hoDanTruocButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(hoDanSauButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(luuHoDanButton)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maHoDanLabel)
                    .addComponent(maHoDanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soNhaLabel)
                    .addComponent(soNhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(luuHoDanButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoDanTruocButton)
                    .addComponent(hoDanSauButton))
                .addGap(15, 15, 15))
        );

        thanhVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã người", "Họ tên", "Tuổi", "Năm sinh", "Nghề nghiệp"
            }
        ));
        jScrollPane1.setViewportView(thanhVienTable);
        if (thanhVienTable.getColumnModel().getColumnCount() > 0) {
            thanhVienTable.getColumnModel().getColumn(2).setMaxWidth(90);
            thanhVienTable.getColumnModel().getColumn(3).setMaxWidth(90);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(suaKhuPhoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(saveKhuPhoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backKhuPhoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenKhuPhoLabel)
                                    .addComponent(maKhuPhoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maKhuPhoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(tenKhuPhoTextField))
                                .addGap(8, 8, 8))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveKhuPhoButton)
                            .addComponent(backKhuPhoButton)))
                    .addComponent(suaKhuPhoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maKhuPhoLabel)
                            .addComponent(maKhuPhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenKhuPhoLabel)
                            .addComponent(tenKhuPhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backKhuPhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backKhuPhoButtonActionPerformed
        KhuPhoFrame frame = new KhuPhoFrame();
        frame.show();
        dispose();
    }//GEN-LAST:event_backKhuPhoButtonActionPerformed

    private void hoDanSauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoDanSauButtonActionPerformed
        HoDanDAO hdDAO = new HoDanDAO();
        List<HoDanModel> listHoDan = hdDAO.findByMaKhuPho(maKhuPhoTextField.getText());
        indexHoDan++;
        int soLuongHoDan = listHoDan.size();
        if(indexHoDan > soLuongHoDan - 1) {
            indexHoDan = 0;
        }
        maHoDanTextField.setText(listHoDan.get(indexHoDan).getMaHoDan());
        soNhaTextField.setText(listHoDan.get(indexHoDan).getSoNha());  
        
        NguoiDAO nguoiDAO = new NguoiDAO();
        List<NguoiModel> listNguoi = nguoiDAO.findByMaHoDan(maHoDanTextField.getText());
        maNguoiTextField.setText(listNguoi.get(0).getMaNguoi());
        hoTenTextField.setText(listNguoi.get(0).getHoVaTen());
        tuoiTextField.setText(Integer.toString(listNguoi.get(0).getTuoi()));
        namSinhTextField.setText(Integer.toString(listNguoi.get(0).getNamSinh()));
        ngheNghiepTextField.setText(listNguoi.get(0).getNgheNghiep());   
        
        tableModel = (DefaultTableModel) thanhVienTable.getModel();
        showTable(listNguoi);
    }//GEN-LAST:event_hoDanSauButtonActionPerformed

    private void hoDanTruocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoDanTruocButtonActionPerformed
        soNhaTextField.setText("");
        HoDanDAO hdDAO = new HoDanDAO();
        List<HoDanModel> listHoDan = hdDAO.findByMaKhuPho(maKhuPhoTextField.getText());
        indexHoDan--;
        int soLuongHoDan = listHoDan.size();
        if(indexHoDan < 0) {
            indexHoDan = listHoDan.size() - 1;
        }
        maHoDanTextField.setText(listHoDan.get(indexHoDan).getMaHoDan());
        soNhaTextField.setText(listHoDan.get(indexHoDan).getSoNha());
        
        NguoiDAO nguoiDAO = new NguoiDAO();
        List<NguoiModel> listNguoi = nguoiDAO.findByMaHoDan(maHoDanTextField.getText());
        maNguoiTextField.setText(listNguoi.get(0).getMaNguoi());
        hoTenTextField.setText(listNguoi.get(0).getHoVaTen());
        tuoiTextField.setText(Integer.toString(listNguoi.get(0).getTuoi()));
        namSinhTextField.setText(Integer.toString(listNguoi.get(0).getNamSinh()));
        ngheNghiepTextField.setText(listNguoi.get(0).getNgheNghiep()); 
        
        tableModel = (DefaultTableModel) thanhVienTable.getModel();
        showTable(listNguoi);
    }//GEN-LAST:event_hoDanTruocButtonActionPerformed

    private void thanhVienSauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhVienSauButtonActionPerformed
        NguoiDAO nguoiDAO = new NguoiDAO();
        List<NguoiModel> listNguoi = nguoiDAO.findByMaHoDan(maHoDanTextField.getText());
        indexNguoi++;
        int soLuongThanhVien = listNguoi.size();
        if(indexNguoi > soLuongThanhVien - 1) {
            indexNguoi = 0;
        }
        maNguoiTextField.setText(listNguoi.get(indexNguoi).getMaNguoi());
        hoTenTextField.setText(listNguoi.get(indexNguoi).getHoVaTen());
        tuoiTextField.setText(Integer.toString(listNguoi.get(indexNguoi).getTuoi()));
        namSinhTextField.setText(Integer.toString(listNguoi.get(indexNguoi).getNamSinh()));
        ngheNghiepTextField.setText(listNguoi.get(indexNguoi).getNgheNghiep()); 
    }//GEN-LAST:event_thanhVienSauButtonActionPerformed

    private void thanhVienTruocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhVienTruocButtonActionPerformed
        NguoiDAO nguoiDAO = new NguoiDAO();
        List<NguoiModel> listNguoi = nguoiDAO.findByMaHoDan(maHoDanTextField.getText());
        indexNguoi--;
        int soLuongThanhVien = listNguoi.size();
        if(indexNguoi < 0) {
            indexNguoi = soLuongThanhVien - 1;
        }
        maNguoiTextField.setText(listNguoi.get(indexNguoi).getMaNguoi());
        hoTenTextField.setText(listNguoi.get(indexNguoi).getHoVaTen());
        tuoiTextField.setText(Integer.toString(listNguoi.get(indexNguoi).getTuoi()));
        namSinhTextField.setText(Integer.toString(listNguoi.get(indexNguoi).getNamSinh()));
        ngheNghiepTextField.setText(listNguoi.get(indexNguoi).getNgheNghiep());
    }//GEN-LAST:event_thanhVienTruocButtonActionPerformed

    private void luuHoDanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuHoDanButtonActionPerformed
        String maHoDan = maHoDanTextField.getText();
        String soNha = soNhaTextField.getText();
        
        HoDanDAO hdDAO = new HoDanDAO();
        if(hdDAO.editHoDan(maHoDan, soNha)) {
            JOptionPane.showMessageDialog(rootPane, "Sửa hộ dân thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sửa hộ dân không thành công");
        }
        
    }//GEN-LAST:event_luuHoDanButtonActionPerformed

    private void luuNguoiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuNguoiButtonActionPerformed
        String maNguoi = maNguoiTextField.getText();
        String hoTen = hoTenTextField.getText();
        int tuoi = Integer.parseInt(tuoiTextField.getText());
        int namSinh = Integer.parseInt(namSinhTextField.getText());
        String ngheNghiep = ngheNghiepTextField.getText();
        String maHoDan = maHoDanTextField.getText();
        
        NguoiModel nguoi = new NguoiModel(maNguoi, hoTen, tuoi, namSinh, ngheNghiep, maHoDan);
        NguoiDAO nguoiDAO = new NguoiDAO();
        if(nguoiDAO.editNguoi(maNguoi, nguoi)) {
            JOptionPane.showMessageDialog(rootPane, "Sửa người dân thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sửa người dân không thành công");
        }
    }//GEN-LAST:event_luuNguoiButtonActionPerformed

    private void saveKhuPhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveKhuPhoButtonActionPerformed
        String maKhuPho = maKhuPhoTextField.getText();
        String tenKhuPho = tenKhuPhoTextField.getText();
        String maHoDan = maHoDanTextField.getText();
        String soNha = soNhaTextField.getText();
        String maNguoi = maNguoiTextField.getText();
        String hoTen = hoTenTextField.getText();
        int tuoi = Integer.parseInt(tuoiTextField.getText());
        int namSinh = Integer.parseInt(namSinhTextField.getText());
        String ngheNghiep = ngheNghiepTextField.getText();
        
        NguoiModel nguoi = new NguoiModel(maNguoi, hoTen, tuoi, namSinh, ngheNghiep, maKhuPho);
        
        KhuPhoDAO kpDAO = new KhuPhoDAO();
        HoDanDAO hdDAO = new HoDanDAO();
        NguoiDAO nguoiDAO = new NguoiDAO();
        
        kpDAO.editKhuPho(maKhuPho, tenKhuPho);
        hdDAO.editHoDan(maHoDan, soNha);
        nguoiDAO.editNguoi(maNguoi, nguoi);
        
        JOptionPane.showMessageDialog(rootPane, "Lưu thành công");
        
        KhuPhoFrame frame = new KhuPhoFrame();
        frame.show();
        dispose();
    }//GEN-LAST:event_saveKhuPhoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaKhuPhoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backKhuPhoButton;
    private javax.swing.JButton hoDanSauButton;
    private javax.swing.JButton hoDanTruocButton;
    private javax.swing.JLabel hoTenLabel;
    protected javax.swing.JTextField hoTenTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luuHoDanButton;
    private javax.swing.JButton luuNguoiButton;
    private javax.swing.JLabel maHoDanLabel;
    protected javax.swing.JTextField maHoDanTextField;
    private javax.swing.JLabel maKhuPhoLabel;
    protected javax.swing.JTextField maKhuPhoTextField;
    private javax.swing.JLabel maNguoiLabel;
    protected javax.swing.JTextField maNguoiTextField;
    private javax.swing.JLabel namSinhLabel;
    protected javax.swing.JTextField namSinhTextField;
    private javax.swing.JLabel ngheNghiepLabel;
    protected javax.swing.JTextField ngheNghiepTextField;
    private javax.swing.JButton saveKhuPhoButton;
    private javax.swing.JLabel soNhaLabel;
    protected javax.swing.JTextField soNhaTextField;
    private javax.swing.JLabel suaKhuPhoLabel;
    private javax.swing.JLabel tenKhuPhoLabel;
    protected javax.swing.JTextField tenKhuPhoTextField;
    private javax.swing.JButton thanhVienSauButton;
    private javax.swing.JTable thanhVienTable;
    private javax.swing.JButton thanhVienTruocButton;
    private javax.swing.JLabel tuoiLabel;
    protected javax.swing.JTextField tuoiTextField;
    // End of variables declaration//GEN-END:variables
}
