package com.mycompany.filnalexam_20182866_nguyenvantuan.view;

import com.mycompany.filnalexam_20182866_nguyenvantuan.controller.Implement.HoDanDAO;
import com.mycompany.filnalexam_20182866_nguyenvantuan.controller.Implement.KhuPhoDAO;
import com.mycompany.filnalexam_20182866_nguyenvantuan.controller.Implement.NguoiDAO;
import com.mycompany.filnalexam_20182866_nguyenvantuan.model.HoDanModel;
import com.mycompany.filnalexam_20182866_nguyenvantuan.model.KhuPhoModel;
import com.mycompany.filnalexam_20182866_nguyenvantuan.model.NguoiModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Van Tuan
 */
public class ThemKhuPhoFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThemKhuPhoFrame
     */
    public ThemKhuPhoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        maKhuPhoLabel = new javax.swing.JLabel();
        maKhuPhoTextField = new javax.swing.JTextField();
        tenKhuPhoLabel = new javax.swing.JLabel();
        tenKhuPhoTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        maHoDanLabel = new javax.swing.JLabel();
        maHoDanTextField = new javax.swing.JTextField();
        soNhaLabel = new javax.swing.JLabel();
        soNhaTextField = new javax.swing.JTextField();
        nhapHoDanButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        maNguoiLabel = new javax.swing.JLabel();
        maNguoiTextField = new javax.swing.JTextField();
        hoTenLabel = new javax.swing.JLabel();
        hoTenTextField = new javax.swing.JTextField();
        tuoiLabel = new javax.swing.JLabel();
        tuoiTextField = new javax.swing.JTextField();
        namSinhLabel = new javax.swing.JLabel();
        namSinhTextField = new javax.swing.JTextField();
        ngheNghiepLabel = new javax.swing.JLabel();
        ngheNghiepTextField = new javax.swing.JTextField();
        nhapThanhVienButton = new javax.swing.JButton();
        hoanThanhButton = new javax.swing.JButton();
        thoatButton = new javax.swing.JButton();
        thongTinNhapLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hienthiTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        maKhuPhoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maKhuPhoLabel.setText("Mã khu phố");

        tenKhuPhoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tenKhuPhoLabel.setText("Tên khu phố");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        maHoDanLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maHoDanLabel.setText("Mã hộ dân");

        soNhaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        soNhaLabel.setText("Số nhà");

        nhapHoDanButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nhapHoDanButton.setText("Tiếp tục nhập hộ dân");
        nhapHoDanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapHoDanButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        maNguoiLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        maNguoiLabel.setText("Mã người");

        hoTenLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hoTenLabel.setText("Họ tên");

        tuoiLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tuoiLabel.setText("Tuổi");

        namSinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namSinhLabel.setText("Năm sinh");

        ngheNghiepLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ngheNghiepLabel.setText("Nghề nghiệp");

        nhapThanhVienButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nhapThanhVienButton.setText("Tiếp tục nhập thành viên");
        nhapThanhVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapThanhVienButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nhapThanhVienButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hoTenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maNguoiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tuoiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namSinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngheNghiepLabel))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maNguoiTextField)
                            .addComponent(hoTenTextField)
                            .addComponent(tuoiTextField)
                            .addComponent(namSinhTextField)
                            .addComponent(ngheNghiepTextField))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNguoiLabel)
                    .addComponent(maNguoiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoTenLabel)
                    .addComponent(hoTenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuoiLabel)
                    .addComponent(tuoiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namSinhLabel)
                    .addComponent(namSinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngheNghiepLabel)
                    .addComponent(ngheNghiepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhapThanhVienButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maHoDanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soNhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maHoDanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(soNhaTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nhapHoDanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maHoDanLabel)
                    .addComponent(maHoDanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soNhaLabel)
                    .addComponent(soNhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhapHoDanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hoanThanhButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hoanThanhButton.setText("Hoàn thành");
        hoanThanhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoanThanhButtonActionPerformed(evt);
            }
        });

        thoatButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thoatButton.setText("Thoát");
        thoatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maKhuPhoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenKhuPhoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tenKhuPhoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(maKhuPhoTextField))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hoanThanhButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thoatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maKhuPhoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maKhuPhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenKhuPhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenKhuPhoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hoanThanhButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(thoatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        thongTinNhapLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thongTinNhapLabel.setText("Thông tin vừa nhập");

        hienthiTextArea.setColumns(20);
        hienthiTextArea.setRows(5);
        jScrollPane1.setViewportView(hienthiTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(thongTinNhapLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(thongTinNhapLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoanThanhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoanThanhButtonActionPerformed
        hienthiTextArea.setText("");
       
        String maKhuPho = maKhuPhoTextField.getText();
        String tenKhuPho = tenKhuPhoTextField.getText();
        String maHoDan = maHoDanTextField.getText();
        String soNha = soNhaTextField.getText();
        String maNguoi = maNguoiTextField.getText();
        String hoTen = hoTenTextField.getText();
        String tuoi = tuoiTextField.getText();
        String namSinh = namSinhTextField.getText();
        String ngheNghiep = ngheNghiepTextField.getText();
        
        
        if(!"".equals(maKhuPho) && !"".equals(tenKhuPho)) {
            KhuPhoDAO kpDAO = new KhuPhoDAO();
            if(kpDAO.findByID(maKhuPho) == null) {
                KhuPhoModel kp = new KhuPhoModel(maKhuPho, tenKhuPho);
                kpDAO.addKhuPho(kp);
            } 
            if(!"".equals(maHoDan) && !"".equals(soNha)) {
                HoDanDAO hdDAO = new HoDanDAO();
                if(hdDAO.findByID(maHoDan) == null) {
                    HoDanModel hd = new HoDanModel(maHoDan, 0, soNha, maKhuPho);
                    hdDAO.addHoDan(hd); 
                }  
                if(!"".equals(maNguoi) && !"".equals(hoTen) && !"".equals(tuoi) && !"".equals(namSinh) && !"".equals(ngheNghiep)) {
                    NguoiDAO nguoiDAO = new NguoiDAO();
                    if(nguoiDAO.findByID(maNguoi) == null){
                        NguoiModel nguoi = new NguoiModel(maNguoi, hoTen, Integer.parseInt(tuoi), Integer.parseInt(namSinh), ngheNghiep, maHoDan);
                        nguoiDAO.addNguoi(nguoi);
                        int soNguoi = hdDAO.getSoThanhVien(maHoDan);
                        soNguoi++;
                        hdDAO.editSoThanhvien(maHoDan, soNguoi);    
                    }   
                }
            }
        } 
        KhuPhoFrame frame = new KhuPhoFrame();
        frame.show();
        dispose();
    }//GEN-LAST:event_hoanThanhButtonActionPerformed

    private void thoatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatButtonActionPerformed
        KhuPhoFrame frame = new KhuPhoFrame();
        frame.show();
        dispose();
    }//GEN-LAST:event_thoatButtonActionPerformed

    public void clearTextFieldNguoi() {
        maNguoiTextField.setText("");
        hoTenTextField.setText("");
        tuoiTextField.setText("");
        namSinhTextField.setText("");
        ngheNghiepTextField.setText("");
    }
    
    public void clearTextFieldHoDan() {
        maHoDanTextField.setText("");
        soNhaTextField.setText("");
    }
    
    private void nhapThanhVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapThanhVienButtonActionPerformed
        hienthiTextArea.setText("");
       
        String maKhuPho = maKhuPhoTextField.getText();
        String tenKhuPho = tenKhuPhoTextField.getText();
        String maHoDan = maHoDanTextField.getText();
        String soNha = soNhaTextField.getText();
        String maNguoi = maNguoiTextField.getText();
        String hoTen = hoTenTextField.getText();
        String tuoi = tuoiTextField.getText();
        String namSinh = namSinhTextField.getText();
        String ngheNghiep = ngheNghiepTextField.getText();
        
        boolean check = true;
        
        
        if("".equals(maKhuPho) || "".equals(tenKhuPho) || "".equals(maHoDan) || "".equals(soNha) || "".equals(maNguoi) || "".equals(hoTen) || "".equals(tuoi) || "".equals(namSinh) || "".equals(ngheNghiep)) {
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập đầy đủ thông tin");
            check = false;
        } else {
            KhuPhoDAO kpDAO = new KhuPhoDAO();
            if(kpDAO.findByID(maKhuPho) == null) {
                KhuPhoModel kp = new KhuPhoModel(maKhuPho, tenKhuPho);
                kpDAO.addKhuPho(kp);
            }
            HoDanDAO hdDAO = new HoDanDAO();
            if(hdDAO.findByID(maHoDan) == null) {
                HoDanModel hd = new HoDanModel(maHoDan, 0, soNha, maKhuPho);
                hdDAO.addHoDan(hd);
            }
            NguoiDAO nguoiDAO = new NguoiDAO();
            if(nguoiDAO.findByID(maNguoi) != null){
                JOptionPane.showMessageDialog(rootPane, "Mã người đã tồn tại");
                check = false;
            } else {
                NguoiModel nguoi = new NguoiModel(maNguoi, hoTen, Integer.parseInt(tuoi), Integer.parseInt(namSinh), ngheNghiep, maHoDan);
                nguoiDAO.addNguoi(nguoi);
                int soNguoi = hdDAO.getSoThanhVien(maHoDan);
                soNguoi++;
                hdDAO.editSoThanhvien(maHoDan, soNguoi);
            }  
        }
        
        if(check) {
            String textField = "- Mã khu phố: " + maKhuPho
                            + "\n- Tên khu phố: " + tenKhuPho
                            + "\n- Mã hộ dân: " + maHoDan
                            + "\n- Số nhà: " + soNha
                            + "\n- Mã người: " + maNguoi
                            + "\n- Họ và tên; " + hoTen
                            + "\n- Tuổi: " + tuoi
                            + "\n- Năm sinh: " + namSinh 
                            + "\n- Nghề nghiệp: " + ngheNghiep;
            hienthiTextArea.setText(textField);
            clearTextFieldNguoi();
        } 
    }//GEN-LAST:event_nhapThanhVienButtonActionPerformed

    private void nhapHoDanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapHoDanButtonActionPerformed
        hienthiTextArea.setText("");
       
        String maKhuPho = maKhuPhoTextField.getText();
        String tenKhuPho = tenKhuPhoTextField.getText();
        String maHoDan = maHoDanTextField.getText();
        String soNha = soNhaTextField.getText();
        
        boolean check = true;
        
        if("".equals(maKhuPho) || "".equals(tenKhuPho) || "".equals(maHoDan) || "".equals(soNha)) {
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập thông tin khu phố, hộ dân");
            check = false;
        } else {
            KhuPhoDAO kpDAO = new KhuPhoDAO();
            if(kpDAO.findByID(maKhuPho) == null) {
                KhuPhoModel kp = new KhuPhoModel(maKhuPho, tenKhuPho);
                kpDAO.addKhuPho(kp);
            }
            HoDanDAO hdDAO = new HoDanDAO();
            if(hdDAO.findByID(maHoDan) != null) {
                JOptionPane.showMessageDialog(rootPane, "Mã hộ dân đã tồn tại"); 
                check = false;
            } else {
                HoDanModel hd = new HoDanModel(maHoDan, 0, soNha, maKhuPho);
                hdDAO.addHoDan(hd);
            }
        }
        if(check) {
            String textField = "- Mã khu phố: " + maKhuPho
                            + "\n- Tên khu phố: " + tenKhuPho
                            + "\n- Mã hộ dân: " + maHoDan
                            + "\n- Số nhà: " + soNha;
            hienthiTextArea.setText(textField);
            clearTextFieldHoDan(); 
        }       
    }//GEN-LAST:event_nhapHoDanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemKhuPhoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemKhuPhoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea hienthiTextArea;
    private javax.swing.JLabel hoTenLabel;
    private javax.swing.JTextField hoTenTextField;
    private javax.swing.JButton hoanThanhButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maHoDanLabel;
    private javax.swing.JTextField maHoDanTextField;
    private javax.swing.JLabel maKhuPhoLabel;
    private javax.swing.JTextField maKhuPhoTextField;
    private javax.swing.JLabel maNguoiLabel;
    private javax.swing.JTextField maNguoiTextField;
    private javax.swing.JLabel namSinhLabel;
    private javax.swing.JTextField namSinhTextField;
    private javax.swing.JLabel ngheNghiepLabel;
    private javax.swing.JTextField ngheNghiepTextField;
    private javax.swing.JButton nhapHoDanButton;
    private javax.swing.JButton nhapThanhVienButton;
    private javax.swing.JLabel soNhaLabel;
    private javax.swing.JTextField soNhaTextField;
    private javax.swing.JLabel tenKhuPhoLabel;
    private javax.swing.JTextField tenKhuPhoTextField;
    private javax.swing.JButton thoatButton;
    private javax.swing.JLabel thongTinNhapLabel;
    private javax.swing.JLabel tuoiLabel;
    private javax.swing.JTextField tuoiTextField;
    // End of variables declaration//GEN-END:variables
}
